### ISSUE TITLE
Problem windows key?

### ISSUE THREAD

**Issue by 00xData** [tkisason/peking_duck#1]
Hello im trying to make ESP_LAT keyboard but wen i conect the bad usb with language_mapping.ino start typing the keys but in the windows key make me a mess and y cant complete the keyboard. Any solution?

thanks

EDIT: I disable windows key to prevent move of the text editor, but still moving from the Notepad, and the last number i can see is  '134':'', after that move and i cant do nothing

**Comment by tkisason** [comment]
Can you please give me more details? I don't understand the problem...

**Comment by jalax0990** [comment]
Sure, first i load  language_mapping.ino to the badusb.
The script run and start maping, and all is good but in the character  '134':'', makes a convination or something that move me away of the notepad and i can have the full characters.

**Comment by jalax0990** [comment]
Hello i upload a video of the problem
[youtu.be/1bWMNPwBHbY](url)


As you can see at 135 a convination move me out of the notepad and i cant have the full keyboard, i try to disable windows key but still doing this.
